<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xhtml="http://www.w3.org/1999/xhtml"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Roliv Studio</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						background-color: #f8fafc;
						margin: 0;
						padding: 40px;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 16px;
						box-shadow: 0 10px 25px rgba(0,0,0,0.05);
					}
					h1 {
						color: #0f172a;
						font-size: 28px;
						margin-bottom: 8px;
						font-weight: 700;
					}
					p.description {
						color: #64748b;
						margin-bottom: 32px;
						line-height: 1.6;
						}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 12px 16px;
						background-color: #f1f5f9;
						color: #475569;
						font-weight: 600;
						font-size: 14px;
						border-bottom: 2px solid #e2e8f0;
					}
					td {
						padding: 14px 16px;
						border-bottom: 1px solid #f1f5f9;
						font-size: 14px;
						line-height: 1.5;
						vertical-align: top;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					a {
						color: #2563eb;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.alternates {
						font-size: 11px;
						color: #94a3b8;
						margin-top: 4px;
					}
					.alternates span {
						display: block;
					}
					.tag {
						display: inline-block;
						padding: 2px 8px;
						border-radius: 4px;
						font-size: 11px;
						font-weight: 600;
						text-transform: uppercase;
					}
					.tag-priority { background: #dcfce7; color: #166534; }
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p class="description">
						Generated by <a href="https://rolivstudio.com">Roliv Studio</a>. This is an XML Sitemap, meant for consumption by search engines.<br/>
						You can find more information about XML sitemaps on <a href="http://sitemaps.org">sitemaps.org</a>.
					</p>
					
					<xsl:if test="sitemap:sitemapindex">
						<p class="description">This is a sitemap index file. It contains links to sub-sitemaps.</p>
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="sitemap:lastmod"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					
					<xsl:if test="sitemap:urlset">
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th>Priority</th>
									<th>Change Freq.</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
											<xsl:if test="xhtml:link">
												<div class="alternates">
													<xsl:for-each select="xhtml:link">
														<span>Alternative (<xsl:value-of select="@hreflang"/>): <xsl:value-of select="@href"/></span>
													</xsl:for-each>
												</div>
											</xsl:if>
										</td>
										<td>
											<span class="tag tag-priority"><xsl:value-of select="sitemap:priority"/></span>
										</td>
										<td>
											<xsl:value-of select="sitemap:changefreq"/>
										</td>
										<td>
											<xsl:value-of select="sitemap:lastmod"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>

</xsl:stylesheet>
